name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: cache
        name: Yarn Cache Dir
        run: echo "value=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Restore Lockfile
        uses: actions/cache@v3
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Install
        run: yarn

      - name: Upload Lockfile
        uses: actions/upload-artifact@v3
        with:
          name: lockfile
          path: yarn.lock

      - name: Build (koishi-plugin-docs)
        run: yarn build
        env:
          DEPLOY_BASE: /dist-docs/

      - name: Deploy (koishi-plugin-docs)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          publish_branch: dist-docs
          publish_dir: .vitepress/dist
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'

      - name: Sync (koishi-plugin-docs)
        run: >
          curl -L
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}"
          https://api.github.com/repos/koishijs/koishi-plugin-docs/actions/workflows/build.yml/dispatches
          -d '{"ref":"main"}'

      - name: Build
        run: yarn build
        env:
          MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILISEARCH_READ_KEY: ${{ secrets.MEILISEARCH_READ_KEY }}
          MEILISEARCH_WRITE_KEY: ${{ secrets.MEILISEARCH_WRITE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          publish_branch: dist
          publish_dir: .vitepress/dist
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'
